swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
schemes:
  - https
basePath: /booster
paths:
  /hello:
    x-swagger-router-controller: hello
    get:
      summary: greeting
      description: greeting message
      operationId: greeting
      responses:
        '200':
          description: OK
  /clients:
    x-swagger-router-controller: hello
    post:
      summary: add clients
      description: add clients
      operationId: addClients
      parameters:
        - in: body
          name: jsonObj
          required: true
          description: the Json Object
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                fileShareLocation:
                  type: string
      consumes: [
          "application/json"
      ]
      responses:
        '200':
          description: OK
